#!/bin/bash
# Deploy a server setup on a EC2 / DO instance
#
# @author Matt Carter <m@ttcarter.com>
# @date 2016-04-11

# Stop on errors
set -euo pipefail

cd ~/crebp-sra.com

echo "Stopping all PM2 child processes..."
pm2 kill

echo "Booting main web server"
NODE_ENV=production
pm2 start server.js

echo "Booting babysitter process"
pm2 start --name babysitter `which pm2-babysitter` -- --app server --url http://localhost -v -d 10000
