#!/bin/bash
# Deploy a server setup on a EC2 / DO instance
#
# @author Matt Carter <m@ttcarter.com>
# @date 2016-04-11

# Stop on errors
set -euo pipefail

cd /sites/sr-accelerator.com

echo "Stopping all PM2 child processes..."
pm2 kill

echo "Booting main web server"
export NODE_ENV=production
PORT=10101 pm2 start --name sra-a --time server.js

export NODE_ENV=slave
PORT=10102 pm2 start --name sra-b --time server.js
PORT=10103 pm2 start --name sra-c --time server.js
PORT=10104 pm2 start --name sra-d --time server.js
