#!/bin/bash
# Renew a letsencrypt / acme cert
# Usage: renew-cert

# Stop on errors
set -euo pipefail

echo "Stopping nginx..."
sudo service nginx stop

echo "Requesting cert renewal via Certbot..."
sudo certbot certonly \
	--cert-name sr-accelerator.com \
	-d sr-accelerator.com \
	-d www.sr-accelerator.com \
	-d searchrefiner.sr-accelerator.com \
	-m matt_carter@bond.edu.au \
	--agree-tos \
	--eff-email \
	--manual-public-ip-logging-ok


echo "Reloading nginx..."
sudo service nginx start
