var monoxide = require('monoxide');

module.exports = monoxide.schema('references', {
	library: {type: 'pointer', ref: 'libraries', indexed: true},
	created: {type: 'date', default: Date.now},
	edited: {type: 'date', default: Date.now},
	tags: [{type: 'pointer', ref: 'referenceTags', indexed: true}],
	type: {type: 'string', default: 'report'},
	title: {type: 'string'},
	journal: {type: 'string'},
	authors: [{type: 'string'}],
	date: {type: 'string'},
	year: {type: 'string'},
	pages: {type: 'string'},
	volume: {type: 'string'},
	number: {type: 'string'},
	isbn: {type: 'string'},
	label: {type: 'string'},
	caption: {type: 'string'},
	address: {type: 'string'},
	keywords: [{type: 'string'}],
	urls: [{type: 'string'}],
	abstract: {type: 'string'},
	notes: {type: 'string'},
	researchNotes: {type: 'string'},
	status: {type: 'string', enum: ['active', 'deleted', 'dupe'], default: 'active', indexed: true},
	fullTextURL: {type: 'string'},
	screening: {
		hash: {type: 'string'},
		weight: {type: 'number'},
	},
	parentage: { // see libraries model for a description of this structure
		parent: {type: 'pointer', ref: 'references', index: true},
		fingerPrint: {type: 'string'},
	},
	duplicateData: [{
		reference: {type: 'pointer', ref: 'references'},
		conflicting: {type: 'object', default: {}},
	}],
});
